filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.postbuffer=524288000
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
user.email=aicmisai@gmail.com
user.name=MIS
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:ACI-MIS-Team/Farmer_Info_Database_App.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.Shuvo.gk-last-accessed=2026-01-13T08:19:05.420Z
branch.Shuvo.gk-last-modified=2026-01-13T08:19:43.919Z
